### ISSUE TITLE
[BUG] Giant white box display Glitch when sorting books by start date/finish date.

### ISSUE THREAD

**Issue by ajensen1234** [mateusz-bak/openreads#451]
**Describe the bug**
A white box fills the entire screen when you try and sort books by start/finish date. It seems to be of infinite size, because you cannot scroll beyond it. It remains even after deleting storage and importing data as both a full import and just a csv, so it must not have anything to do with the covers. It only effects certain books, not all.

**To Reproduce**
Install release 2.4 from GitHub (obtanium).
Import books
Sort by start/finish date.

**Expected behavior**
I expected to see the normal pages as they've always been present.

**Screenshots**
If applicable, add screenshots to help explain your problem.![Screenshot_20240206-073440.png](https://github.com/mateusz-bak/openreads/assets/63751488/5acd276f-b407-4f26-ba9b-246af27dccca)
![Screenshot_20240206-073956.png](https://github.com/mateusz-bak/openreads/assets/63751488/5619f300-c8de-4ec0-b5d5-2657b89c23c7)
![Screenshot_20240206-073932.png](https://github.com/mateusz-bak/openreads/assets/63751488/8c133860-d382-4f0a-9d39-7f3fadac3ac4)

**Additional info(please complete the following information):**
- App version: 2.4.0
- App source (F-Droid, Google Play, Github, AppStore): GitHub (via obtanium)
- Manufacturer and model: Google Pixel 7 Pro
- OS and version: GrapheneOS, 2024012600

**Additional context**

**Comment by mateusz-bak** [comment]
Thanks for reporting, I observed the same and doing the fix now

**Comment by mateusz-bak** [comment]
Should be fixed in 2.4.1

**Comment by ajensen1234** [comment]
Thanks a ton! I appreciate all your work on this outstanding app!

**Comment by smlpt** [comment]
Hey @mateusz-bak, I fear this is not quite solved yet.
I downloaded 2.4.1 today, added a second start reading date to a book and changed it to "in progress":

<img src="https://github.com/mateusz-bak/openreads/assets/83579186/afaf30ae-c4c0-49a4-ab03-803682446833" width="300">

As soon as I add a finish date, the grey box is gone. It also only happens when the sort order includes the date.

It gets even worse when you move the book to "finished" without adding an end reading date:

<img src="https://github.com/mateusz-bak/openreads/assets/83579186/7a18ecd9-56a7-4cd0-87e1-a4df4ea7602f" width="300">

This basically makes the whole list/grid view unclickable and right now the only temporary solution is to not use either the start or finish date for the sort order.

**Comment by mateusz-bak** [comment]
Thanks @smlpt will work on this today

**Comment by mateusz-bak** [comment]
The code was getting the latest start/finish date by going through all readings.

If the reading would not have start or finish date set it would crash.
Now it goes only through the readings that have finish or start date set when needed.

I think this will work now and will be released in 2.5.1

**Comment by smlpt** [comment]
Thank you!

**Comment by ajensen1234** [comment]
@mateusz-bak this issue has come back for me, unfortunately, in 2.5.1 :(

![Screenshot_20240228-171835.png](https://github.com/mateusz-bak/openreads/assets/63751488/0612376b-481d-4dd0-a1fd-e8b98ef4ee4a)

![Screenshot_20240228-171832.png](https://github.com/mateusz-bak/openreads/assets/63751488/764e6325-7213-4cf9-bdab-c5fb7fd0303e)

**Comment by mateusz-bak** [comment]
Okay, I reproduced it now
